vote_backend_build_on_target: true

vote_backend_postgres_persistent: true

vote_backend_nginx_enabled: true

vote_backend_acme_enabled: false

#Set large limits for dev instance

vote_backend_password_reset_max_attempts: 50
vote_backend_password_reset_rate_limit_window_minutes: 15
vote_backend_password_reset_rate_limit_max_requests: 50

vote_backend_app_reset_url: "http://127.0.0.1:8081/"

vote_backend_allowed_origin: "http://127.0.0.1:8081"
