/**
 *
 *  RestfulUserAnswersCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulUserAnswersCtrl.h"

#include <string>

void RestfulUserAnswersCtrl::getOne(
    const HttpRequestPtr& req,
    std::function<void(const HttpResponsePtr&)>&& callback,
    UserAnswers::PrimaryKeyType&& id) {
  RestfulUserAnswersCtrlBase::getOne(req, std::move(callback), std::move(id));
}

void RestfulUserAnswersCtrl::updateOne(
    const HttpRequestPtr& req,
    std::function<void(const HttpResponsePtr&)>&& callback,
    UserAnswers::PrimaryKeyType&& id) {
  RestfulUserAnswersCtrlBase::updateOne(req, std::move(callback),
                                        std::move(id));
}

void RestfulUserAnswersCtrl::deleteOne(
    const HttpRequestPtr& req,
    std::function<void(const HttpResponsePtr&)>&& callback,
    UserAnswers::PrimaryKeyType&& id) {
  RestfulUserAnswersCtrlBase::deleteOne(req, std::move(callback),
                                        std::move(id));
}

void RestfulUserAnswersCtrl::get(
    const HttpRequestPtr& req,
    std::function<void(const HttpResponsePtr&)>&& callback) {
  RestfulUserAnswersCtrlBase::get(req, std::move(callback));
}

void RestfulUserAnswersCtrl::create(
    const HttpRequestPtr& req,
    std::function<void(const HttpResponsePtr&)>&& callback) {
  RestfulUserAnswersCtrlBase::create(req, std::move(callback));
}
