/**
 *
 *  RestfulUserAnswersCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulUserAnswersCtrlBase.h"

#include "vote-backend/models/UserAnswers.h"
using namespace drogon;
using namespace drogon_model::vote;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the user_answers table.
 */

class RestfulUserAnswersCtrl: public drogon::HttpController<RestfulUserAnswersCtrl>, public RestfulUserAnswersCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulUserAnswersCtrl::getOne,"/useranswers/{1}",Get,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulUserAnswersCtrl::updateOne,"/useranswers/{1}",Put,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulUserAnswersCtrl::deleteOne,"/useranswers/{1}",Delete,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulUserAnswersCtrl::get,"/useranswers",Get,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulUserAnswersCtrl::create,"/useranswers",Post,Options,"JwtAuthFilter");
    //ADD_METHOD_TO(RestfulUserAnswersCtrl::update,"/useranswers",Put,Options,"JwtAuthFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                UserAnswers::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   UserAnswers::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   UserAnswers::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
