/**
 *
 *  RestfulLanguagesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulLanguagesCtrl.h"
#include <string>


void RestfulLanguagesCtrl::getOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Languages::PrimaryKeyType &&id)
{
    RestfulLanguagesCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulLanguagesCtrl::updateOne(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback,
                                     Languages::PrimaryKeyType &&id)
{
    RestfulLanguagesCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulLanguagesCtrl::deleteOne(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback,
                                     Languages::PrimaryKeyType &&id)
{
    RestfulLanguagesCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulLanguagesCtrl::get(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulLanguagesCtrlBase::get(req, std::move(callback));
}

void RestfulLanguagesCtrl::create(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulLanguagesCtrlBase::create(req, std::move(callback));
}
