/**
 *
 *  RestfulQuestionsCtrl.cc
 *
 *  This file is generated by drogon_ctl. The non-generated GET/POST handlers
 *  (get, getOne, create) have been moved to QuestionController so that this
 *  generated controller can eventually be retired. Only the delegating
 *  PUT/DELETE handlers remain here, forwarding to the generated base
 *  (RestfulQuestionsCtrlBase).
 *
 *  Submission / approval workflow (Option B):
 *    - POST /questions stores a *pending* question owned by the authenticated
 *      user (handled in QuestionController now).
 *    - GET /questions and GET /questions/{id} only return *approved* questions
 *      to the public (handled in QuestionController now). Submitters see their
 *      own via GET /questions/mine; admins see the review queue via
 *      GET /admin/questions/submissions (both in QuestionController).
 */

#include "RestfulQuestionsCtrl.h"

void RestfulQuestionsCtrl::updateOne(
    const HttpRequestPtr& req,
    std::function<void(const HttpResponsePtr&)>&& callback,
    Questions::PrimaryKeyType&& id) {
  // Content edits only; submission_status is intentionally not exposed here so
  // users cannot self-approve. Delegates to the generated base handler.
  RestfulQuestionsCtrlBase::updateOne(req, std::move(callback), std::move(id));
}

void RestfulQuestionsCtrl::deleteOne(
    const HttpRequestPtr& req,
    std::function<void(const HttpResponsePtr&)>&& callback,
    Questions::PrimaryKeyType&& id) {
  // Delegates to the generated base handler.
  RestfulQuestionsCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}
