/**
 *
 *  RestfulCategoriesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulCategoriesCtrl.h"
#include <string>


void RestfulCategoriesCtrl::getOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Categories::PrimaryKeyType &&id)
{
    RestfulCategoriesCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulCategoriesCtrl::updateOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      Categories::PrimaryKeyType &&id)
{
    RestfulCategoriesCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulCategoriesCtrl::deleteOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      Categories::PrimaryKeyType &&id)
{
    RestfulCategoriesCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulCategoriesCtrl::get(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulCategoriesCtrlBase::get(req, std::move(callback));
}

void RestfulCategoriesCtrl::create(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulCategoriesCtrlBase::create(req, std::move(callback));
}
