/**
 *
 *  RestfulQuestionsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulQuestionsCtrlBase.h"

#include "vote-backend/models/Questions.h"
using namespace drogon;
using namespace drogon_model::vote;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the questions table.
 */

class RestfulQuestionsCtrl: public drogon::HttpController<RestfulQuestionsCtrl>, public RestfulQuestionsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulQuestionsCtrl::getOne,"/questions/{1}",Get,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulQuestionsCtrl::updateOne,"/questions/{1}",Put,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulQuestionsCtrl::deleteOne,"/questions/{1}",Delete,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulQuestionsCtrl::get,"/questions",Get,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulQuestionsCtrl::create,"/questions",Post,Options,"JwtAuthFilter");
    //ADD_METHOD_TO(RestfulQuestionsCtrl::update,"/questions",Put,Options,"JwtAuthFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Questions::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Questions::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Questions::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
