/**
 *
 *  RestfulAnswerOptionsCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulAnswerOptionsCtrlBase.h"

#include "vote-backend/models/AnswerOptions.h"
using namespace drogon;
using namespace drogon_model::vote;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the answer_options table.
 */

class RestfulAnswerOptionsCtrl: public drogon::HttpController<RestfulAnswerOptionsCtrl>, public RestfulAnswerOptionsCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulAnswerOptionsCtrl::getOne,"/answeroptions/{1}",Get,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulAnswerOptionsCtrl::updateOne,"/answeroptions/{1}",Put,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulAnswerOptionsCtrl::deleteOne,"/answeroptions/{1}",Delete,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulAnswerOptionsCtrl::get,"/answeroptions",Get,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulAnswerOptionsCtrl::create,"/answeroptions",Post,Options,"JwtAuthFilter");
    //ADD_METHOD_TO(RestfulAnswerOptionsCtrl::update,"/answeroptions",Put,Options,"JwtAuthFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                AnswerOptions::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   AnswerOptions::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   AnswerOptions::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
