/**
 *
 *  RestfulLanguagesCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulLanguagesCtrlBase.h"

#include "Languages.h"
using namespace drogon;
using namespace drogon_model::vote;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the languages table.
 */

class RestfulLanguagesCtrl: public drogon::HttpController<RestfulLanguagesCtrl>, public RestfulLanguagesCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulLanguagesCtrl::getOne,"/languages/{1}",Get,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulLanguagesCtrl::updateOne,"/languages/{1}",Put,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulLanguagesCtrl::deleteOne,"/languages/{1}",Delete,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulLanguagesCtrl::get,"/languages",Get,Options,"JwtAuthFilter");
    ADD_METHOD_TO(RestfulLanguagesCtrl::create,"/languages",Post,Options,"JwtAuthFilter");
    //ADD_METHOD_TO(RestfulLanguagesCtrl::update,"/languages",Put,Options,"JwtAuthFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Languages::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Languages::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Languages::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
