all:
  children:
    dev:
      hosts:
        localhost:
          ansible_connection: local
    prod:
      hosts:
        vote_backend:
          ansible_connection: ssh
          ansible_user: mpeschke
