/**
 *
 *  Languages.cpp
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "vote-backend/models/Languages.hpp"

#include <drogon/utils/Utilities.h>

#include <string>

#include "vote-backend/models/Questions.hpp"

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::vote;

const std::string Languages::Cols::_code = "\"code\"";
const std::string Languages::Cols::_name = "\"name\"";
const std::string Languages::primaryKeyName = "code";
const bool Languages::hasPrimaryKey = true;
const std::string Languages::tableName = "\"languages\"";

const std::vector<typename Languages::MetaData> Languages::metaData_ = {
    {"code", "std::string", "character", 0, 0, 1, 1},
    {"name", "std::string", "text", 0, 0, 0, 1}};
const std::string& Languages::getColumnName(size_t index) noexcept(false) {
  assert(index < metaData_.size());
  return metaData_[index].colName_;
}
Languages::Languages(const Row& r, const ssize_t indexOffset) noexcept {
  if (indexOffset < 0) {
    if (!r["code"].isNull()) {
      code_ = std::make_shared<std::string>(r["code"].as<std::string>());
    }
    if (!r["name"].isNull()) {
      name_ = std::make_shared<std::string>(r["name"].as<std::string>());
    }
  } else {
    size_t offset = (size_t)indexOffset;
    if (offset + 2 > r.size()) {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if (!r[index].isNull()) {
      code_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 1;
    if (!r[index].isNull()) {
      name_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
  }
}

Languages::Languages(
    const Json::Value& pJson,
    const std::vector<std::string>& pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 2) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() &&
      pJson.isMember(pMasqueradingVector[0])) {
    dirtyFlag_[0] = true;
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      code_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[0]].asString());
    }
  }
  if (!pMasqueradingVector[1].empty() &&
      pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      name_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[1]].asString());
    }
  }
}

Languages::Languages(const Json::Value& pJson) noexcept(false) {
  if (pJson.isMember("code")) {
    dirtyFlag_[0] = true;
    if (!pJson["code"].isNull()) {
      code_ = std::make_shared<std::string>(pJson["code"].asString());
    }
  }
  if (pJson.isMember("name")) {
    dirtyFlag_[1] = true;
    if (!pJson["name"].isNull()) {
      name_ = std::make_shared<std::string>(pJson["name"].asString());
    }
  }
}

void Languages::updateByMasqueradedJson(
    const Json::Value& pJson,
    const std::vector<std::string>& pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 2) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() &&
      pJson.isMember(pMasqueradingVector[0])) {
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      code_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[0]].asString());
    }
  }
  if (!pMasqueradingVector[1].empty() &&
      pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      name_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[1]].asString());
    }
  }
}

void Languages::updateByJson(const Json::Value& pJson) noexcept(false) {
  if (pJson.isMember("code")) {
    if (!pJson["code"].isNull()) {
      code_ = std::make_shared<std::string>(pJson["code"].asString());
    }
  }
  if (pJson.isMember("name")) {
    dirtyFlag_[1] = true;
    if (!pJson["name"].isNull()) {
      name_ = std::make_shared<std::string>(pJson["name"].asString());
    }
  }
}

const std::string& Languages::getValueOfCode() const noexcept {
  static const std::string defaultValue = std::string();
  if (code_) return *code_;
  return defaultValue;
}
const std::shared_ptr<std::string>& Languages::getCode() const noexcept {
  return code_;
}
void Languages::setCode(const std::string& pCode) noexcept {
  code_ = std::make_shared<std::string>(pCode);
  dirtyFlag_[0] = true;
}
void Languages::setCode(std::string&& pCode) noexcept {
  code_ = std::make_shared<std::string>(std::move(pCode));
  dirtyFlag_[0] = true;
}
const typename Languages::PrimaryKeyType& Languages::getPrimaryKey() const {
  assert(code_);
  return *code_;
}

const std::string& Languages::getValueOfName() const noexcept {
  static const std::string defaultValue = std::string();
  if (name_) return *name_;
  return defaultValue;
}
const std::shared_ptr<std::string>& Languages::getName() const noexcept {
  return name_;
}
void Languages::setName(const std::string& pName) noexcept {
  name_ = std::make_shared<std::string>(pName);
  dirtyFlag_[1] = true;
}
void Languages::setName(std::string&& pName) noexcept {
  name_ = std::make_shared<std::string>(std::move(pName));
  dirtyFlag_[1] = true;
}

void Languages::updateId(const uint64_t id) {}

const std::vector<std::string>& Languages::insertColumns() noexcept {
  static const std::vector<std::string> inCols = {"code", "name"};
  return inCols;
}

void Languages::outputArgs(drogon::orm::internal::SqlBinder& binder) const {
  if (dirtyFlag_[0]) {
    if (getCode()) {
      binder << getValueOfCode();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[1]) {
    if (getName()) {
      binder << getValueOfName();
    } else {
      binder << nullptr;
    }
  }
}

const std::vector<std::string> Languages::updateColumns() const {
  std::vector<std::string> ret;
  if (dirtyFlag_[0]) {
    ret.push_back(getColumnName(0));
  }
  if (dirtyFlag_[1]) {
    ret.push_back(getColumnName(1));
  }
  return ret;
}

void Languages::updateArgs(drogon::orm::internal::SqlBinder& binder) const {
  if (dirtyFlag_[0]) {
    if (getCode()) {
      binder << getValueOfCode();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[1]) {
    if (getName()) {
      binder << getValueOfName();
    } else {
      binder << nullptr;
    }
  }
}
Json::Value Languages::toJson() const {
  Json::Value ret;
  if (getCode()) {
    ret["code"] = getValueOfCode();
  } else {
    ret["code"] = Json::Value();
  }
  if (getName()) {
    ret["name"] = getValueOfName();
  } else {
    ret["name"] = Json::Value();
  }
  return ret;
}

std::string Languages::toString() const { return toJson().toStyledString(); }

Json::Value Languages::toMasqueradedJson(
    const std::vector<std::string>& pMasqueradingVector) const {
  Json::Value ret;
  if (pMasqueradingVector.size() == 2) {
    if (!pMasqueradingVector[0].empty()) {
      if (getCode()) {
        ret[pMasqueradingVector[0]] = getValueOfCode();
      } else {
        ret[pMasqueradingVector[0]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (getName()) {
        ret[pMasqueradingVector[1]] = getValueOfName();
      } else {
        ret[pMasqueradingVector[1]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if (getCode()) {
    ret["code"] = getValueOfCode();
  } else {
    ret["code"] = Json::Value();
  }
  if (getName()) {
    ret["name"] = getValueOfName();
  } else {
    ret["name"] = Json::Value();
  }
  return ret;
}

bool Languages::validateJsonForCreation(const Json::Value& pJson,
                                        std::string& err) {
  if (pJson.isMember("code")) {
    if (!validJsonOfField(0, "code", pJson["code"], err, true)) return false;
  } else {
    err = "The code column cannot be null";
    return false;
  }
  if (pJson.isMember("name")) {
    if (!validJsonOfField(1, "name", pJson["name"], err, true)) return false;
  } else {
    err = "The name column cannot be null";
    return false;
  }
  return true;
}
bool Languages::validateMasqueradedJsonForCreation(
    const Json::Value& pJson,
    const std::vector<std::string>& pMasqueradingVector, std::string& err) {
  if (pMasqueradingVector.size() != 2) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty()) {
      if (pJson.isMember(pMasqueradingVector[0])) {
        if (!validJsonOfField(0, pMasqueradingVector[0],
                              pJson[pMasqueradingVector[0]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[0] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (pJson.isMember(pMasqueradingVector[1])) {
        if (!validJsonOfField(1, pMasqueradingVector[1],
                              pJson[pMasqueradingVector[1]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[1] + " column cannot be null";
        return false;
      }
    }
  } catch (const Json::LogicError& e) {
    err = e.what();
    return false;
  }
  return true;
}
bool Languages::validateJsonForUpdate(const Json::Value& pJson,
                                      std::string& err) {
  if (pJson.isMember("code")) {
    if (!validJsonOfField(0, "code", pJson["code"], err, false)) return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("name")) {
    if (!validJsonOfField(1, "name", pJson["name"], err, false)) return false;
  }
  return true;
}
bool Languages::validateMasqueradedJsonForUpdate(
    const Json::Value& pJson,
    const std::vector<std::string>& pMasqueradingVector, std::string& err) {
  if (pMasqueradingVector.size() != 2) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty() &&
        pJson.isMember(pMasqueradingVector[0])) {
      if (!validJsonOfField(0, pMasqueradingVector[0],
                            pJson[pMasqueradingVector[0]], err, false))
        return false;
    } else {
      err =
          "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[1].empty() &&
        pJson.isMember(pMasqueradingVector[1])) {
      if (!validJsonOfField(1, pMasqueradingVector[1],
                            pJson[pMasqueradingVector[1]], err, false))
        return false;
    }
  } catch (const Json::LogicError& e) {
    err = e.what();
    return false;
  }
  return true;
}
bool Languages::validJsonOfField(size_t index, const std::string& fieldName,
                                 const Json::Value& pJson, std::string& err,
                                 bool isForCreation) {
  switch (index) {
    case 0:
      if (pJson.isNull()) {
        err = "The " + fieldName + " column cannot be null";
        return false;
      }
      if (!pJson.isString()) {
        err = "Type error in the " + fieldName + " field";
        return false;
      }
      break;
    case 1:
      if (pJson.isNull()) {
        err = "The " + fieldName + " column cannot be null";
        return false;
      }
      if (!pJson.isString()) {
        err = "Type error in the " + fieldName + " field";
        return false;
      }
      break;
    default:
      err = "Internal error in the server";
      return false;
  }
  return true;
}
std::vector<Questions> Languages::getQuestions(
    const DbClientPtr& clientPtr) const {
  static const std::string sql = "select * from questions where language = $1";
  Result r(nullptr);
  {
    auto binder = *clientPtr << sql;
    binder << *code_ << Mode::Blocking >>
        [&r](const Result& result) { r = result; };
    binder.exec();
  }
  std::vector<Questions> ret;
  ret.reserve(r.size());
  for (auto const& row : r) {
    ret.emplace_back(Questions(row));
  }
  return ret;
}

void Languages::getQuestions(
    const DbClientPtr& clientPtr,
    const std::function<void(std::vector<Questions>)>& rcb,
    const ExceptionCallback& ecb) const {
  static const std::string sql = "select * from questions where language = $1";
  *clientPtr << sql << *code_ >> [rcb = std::move(rcb)](const Result& r) {
    std::vector<Questions> ret;
    ret.reserve(r.size());
    for (auto const& row : r) {
      ret.emplace_back(Questions(row));
    }
    rcb(ret);
  } >> ecb;
}
