/**
 *
 *  Questions.cpp
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "vote-backend/models/Questions.hpp"

#include <drogon/utils/Utilities.h>

#include <string>

#include "vote-backend/models/AnswerOptions.hpp"
#include "vote-backend/models/Categories.hpp"
#include "vote-backend/models/Languages.hpp"
#include "vote-backend/models/UserAnswers.hpp"

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::vote;

const std::string Questions::Cols::_id = "\"id\"";
const std::string Questions::Cols::_text = "\"text\"";
const std::string Questions::Cols::_category_id = "\"category_id\"";
const std::string Questions::Cols::_language = "\"language\"";
const std::string Questions::Cols::_min_age = "\"min_age\"";
const std::string Questions::Cols::_created_at = "\"created_at\"";
const std::string Questions::primaryKeyName = "id";
const bool Questions::hasPrimaryKey = true;
const std::string Questions::tableName = "\"questions\"";

const std::vector<typename Questions::MetaData> Questions::metaData_ = {
    {"id", "int64_t", "bigint", 8, 1, 1, 1},
    {"text", "std::string", "text", 0, 0, 0, 1},
    {"category_id", "int64_t", "bigint", 8, 0, 0, 1},
    {"language", "std::string", "character", 0, 0, 0, 1},
    {"min_age", "int32_t", "integer", 4, 0, 0, 1},
    {"created_at", "::trantor::Date", "timestamp with time zone", 0, 0, 0, 1}};
const std::string& Questions::getColumnName(size_t index) noexcept(false) {
  assert(index < metaData_.size());
  return metaData_[index].colName_;
}
Questions::Questions(const Row& r, const ssize_t indexOffset) noexcept {
  if (indexOffset < 0) {
    if (!r["id"].isNull()) {
      id_ = std::make_shared<int64_t>(r["id"].as<int64_t>());
    }
    if (!r["text"].isNull()) {
      text_ = std::make_shared<std::string>(r["text"].as<std::string>());
    }
    if (!r["category_id"].isNull()) {
      categoryId_ = std::make_shared<int64_t>(r["category_id"].as<int64_t>());
    }
    if (!r["language"].isNull()) {
      language_ =
          std::make_shared<std::string>(r["language"].as<std::string>());
    }
    if (!r["min_age"].isNull()) {
      minAge_ = std::make_shared<int32_t>(r["min_age"].as<int32_t>());
    }
    if (!r["created_at"].isNull()) {
      auto timeStr = r["created_at"].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  } else {
    size_t offset = (size_t)indexOffset;
    if (offset + 6 > r.size()) {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if (!r[index].isNull()) {
      id_ = std::make_shared<int64_t>(r[index].as<int64_t>());
    }
    index = offset + 1;
    if (!r[index].isNull()) {
      text_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 2;
    if (!r[index].isNull()) {
      categoryId_ = std::make_shared<int64_t>(r[index].as<int64_t>());
    }
    index = offset + 3;
    if (!r[index].isNull()) {
      language_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
    index = offset + 4;
    if (!r[index].isNull()) {
      minAge_ = std::make_shared<int32_t>(r[index].as<int32_t>());
    }
    index = offset + 5;
    if (!r[index].isNull()) {
      auto timeStr = r[index].as<std::string>();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

Questions::Questions(
    const Json::Value& pJson,
    const std::vector<std::string>& pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 6) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() &&
      pJson.isMember(pMasqueradingVector[0])) {
    dirtyFlag_[0] = true;
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int64_t>(
          (int64_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() &&
      pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      text_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() &&
      pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      categoryId_ = std::make_shared<int64_t>(
          (int64_t)pJson[pMasqueradingVector[2]].asInt64());
    }
  }
  if (!pMasqueradingVector[3].empty() &&
      pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      language_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[3]].asString());
    }
  }
  if (!pMasqueradingVector[4].empty() &&
      pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      minAge_ = std::make_shared<int32_t>(
          (int32_t)pJson[pMasqueradingVector[4]].asInt64());
    }
  }
  if (!pMasqueradingVector[5].empty() &&
      pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[5]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

Questions::Questions(const Json::Value& pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    dirtyFlag_[0] = true;
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("text")) {
    dirtyFlag_[1] = true;
    if (!pJson["text"].isNull()) {
      text_ = std::make_shared<std::string>(pJson["text"].asString());
    }
  }
  if (pJson.isMember("category_id")) {
    dirtyFlag_[2] = true;
    if (!pJson["category_id"].isNull()) {
      categoryId_ =
          std::make_shared<int64_t>((int64_t)pJson["category_id"].asInt64());
    }
  }
  if (pJson.isMember("language")) {
    dirtyFlag_[3] = true;
    if (!pJson["language"].isNull()) {
      language_ = std::make_shared<std::string>(pJson["language"].asString());
    }
  }
  if (pJson.isMember("min_age")) {
    dirtyFlag_[4] = true;
    if (!pJson["min_age"].isNull()) {
      minAge_ = std::make_shared<int32_t>((int32_t)pJson["min_age"].asInt64());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[5] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void Questions::updateByMasqueradedJson(
    const Json::Value& pJson,
    const std::vector<std::string>& pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 6) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() &&
      pJson.isMember(pMasqueradingVector[0])) {
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<int64_t>(
          (int64_t)pJson[pMasqueradingVector[0]].asInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() &&
      pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      text_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[1]].asString());
    }
  }
  if (!pMasqueradingVector[2].empty() &&
      pJson.isMember(pMasqueradingVector[2])) {
    dirtyFlag_[2] = true;
    if (!pJson[pMasqueradingVector[2]].isNull()) {
      categoryId_ = std::make_shared<int64_t>(
          (int64_t)pJson[pMasqueradingVector[2]].asInt64());
    }
  }
  if (!pMasqueradingVector[3].empty() &&
      pJson.isMember(pMasqueradingVector[3])) {
    dirtyFlag_[3] = true;
    if (!pJson[pMasqueradingVector[3]].isNull()) {
      language_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[3]].asString());
    }
  }
  if (!pMasqueradingVector[4].empty() &&
      pJson.isMember(pMasqueradingVector[4])) {
    dirtyFlag_[4] = true;
    if (!pJson[pMasqueradingVector[4]].isNull()) {
      minAge_ = std::make_shared<int32_t>(
          (int32_t)pJson[pMasqueradingVector[4]].asInt64());
    }
  }
  if (!pMasqueradingVector[5].empty() &&
      pJson.isMember(pMasqueradingVector[5])) {
    dirtyFlag_[5] = true;
    if (!pJson[pMasqueradingVector[5]].isNull()) {
      auto timeStr = pJson[pMasqueradingVector[5]].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

void Questions::updateByJson(const Json::Value& pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
    }
  }
  if (pJson.isMember("text")) {
    dirtyFlag_[1] = true;
    if (!pJson["text"].isNull()) {
      text_ = std::make_shared<std::string>(pJson["text"].asString());
    }
  }
  if (pJson.isMember("category_id")) {
    dirtyFlag_[2] = true;
    if (!pJson["category_id"].isNull()) {
      categoryId_ =
          std::make_shared<int64_t>((int64_t)pJson["category_id"].asInt64());
    }
  }
  if (pJson.isMember("language")) {
    dirtyFlag_[3] = true;
    if (!pJson["language"].isNull()) {
      language_ = std::make_shared<std::string>(pJson["language"].asString());
    }
  }
  if (pJson.isMember("min_age")) {
    dirtyFlag_[4] = true;
    if (!pJson["min_age"].isNull()) {
      minAge_ = std::make_shared<int32_t>((int32_t)pJson["min_age"].asInt64());
    }
  }
  if (pJson.isMember("created_at")) {
    dirtyFlag_[5] = true;
    if (!pJson["created_at"].isNull()) {
      auto timeStr = pJson["created_at"].asString();
      struct tm stm;
      memset(&stm, 0, sizeof(stm));
      auto p = strptime(timeStr.c_str(), "%Y-%m-%d %H:%M:%S", &stm);
      time_t t = mktime(&stm);
      size_t decimalNum = 0;
      if (p) {
        if (*p == '.') {
          std::string decimals(p + 1, &timeStr[timeStr.length()]);
          while (decimals.length() < 6) {
            decimals += "0";
          }
          decimalNum = (size_t)atol(decimals.c_str());
        }
        createdAt_ =
            std::make_shared<::trantor::Date>(t * 1000000 + decimalNum);
      }
    }
  }
}

const int64_t& Questions::getValueOfId() const noexcept {
  static const int64_t defaultValue = int64_t();
  if (id_) return *id_;
  return defaultValue;
}
const std::shared_ptr<int64_t>& Questions::getId() const noexcept {
  return id_;
}
void Questions::setId(const int64_t& pId) noexcept {
  id_ = std::make_shared<int64_t>(pId);
  dirtyFlag_[0] = true;
}
const typename Questions::PrimaryKeyType& Questions::getPrimaryKey() const {
  assert(id_);
  return *id_;
}

const std::string& Questions::getValueOfText() const noexcept {
  static const std::string defaultValue = std::string();
  if (text_) return *text_;
  return defaultValue;
}
const std::shared_ptr<std::string>& Questions::getText() const noexcept {
  return text_;
}
void Questions::setText(const std::string& pText) noexcept {
  text_ = std::make_shared<std::string>(pText);
  dirtyFlag_[1] = true;
}
void Questions::setText(std::string&& pText) noexcept {
  text_ = std::make_shared<std::string>(std::move(pText));
  dirtyFlag_[1] = true;
}

const int64_t& Questions::getValueOfCategoryId() const noexcept {
  static const int64_t defaultValue = int64_t();
  if (categoryId_) return *categoryId_;
  return defaultValue;
}
const std::shared_ptr<int64_t>& Questions::getCategoryId() const noexcept {
  return categoryId_;
}
void Questions::setCategoryId(const int64_t& pCategoryId) noexcept {
  categoryId_ = std::make_shared<int64_t>(pCategoryId);
  dirtyFlag_[2] = true;
}

const std::string& Questions::getValueOfLanguage() const noexcept {
  static const std::string defaultValue = std::string();
  if (language_) return *language_;
  return defaultValue;
}
const std::shared_ptr<std::string>& Questions::getLanguage() const noexcept {
  return language_;
}
void Questions::setLanguage(const std::string& pLanguage) noexcept {
  language_ = std::make_shared<std::string>(pLanguage);
  dirtyFlag_[3] = true;
}
void Questions::setLanguage(std::string&& pLanguage) noexcept {
  language_ = std::make_shared<std::string>(std::move(pLanguage));
  dirtyFlag_[3] = true;
}

const int32_t& Questions::getValueOfMinAge() const noexcept {
  static const int32_t defaultValue = int32_t();
  if (minAge_) return *minAge_;
  return defaultValue;
}
const std::shared_ptr<int32_t>& Questions::getMinAge() const noexcept {
  return minAge_;
}
void Questions::setMinAge(const int32_t& pMinAge) noexcept {
  minAge_ = std::make_shared<int32_t>(pMinAge);
  dirtyFlag_[4] = true;
}

const ::trantor::Date& Questions::getValueOfCreatedAt() const noexcept {
  static const ::trantor::Date defaultValue = ::trantor::Date();
  if (createdAt_) return *createdAt_;
  return defaultValue;
}
const std::shared_ptr<::trantor::Date>& Questions::getCreatedAt()
    const noexcept {
  return createdAt_;
}
void Questions::setCreatedAt(const ::trantor::Date& pCreatedAt) noexcept {
  createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
  dirtyFlag_[5] = true;
}

void Questions::updateId(const uint64_t id) {}

const std::vector<std::string>& Questions::insertColumns() noexcept {
  static const std::vector<std::string> inCols = {
      "text", "category_id", "language", "min_age", "created_at"};
  return inCols;
}

void Questions::outputArgs(drogon::orm::internal::SqlBinder& binder) const {
  if (dirtyFlag_[1]) {
    if (getText()) {
      binder << getValueOfText();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getCategoryId()) {
      binder << getValueOfCategoryId();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getLanguage()) {
      binder << getValueOfLanguage();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getMinAge()) {
      binder << getValueOfMinAge();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
}

const std::vector<std::string> Questions::updateColumns() const {
  std::vector<std::string> ret;
  if (dirtyFlag_[1]) {
    ret.push_back(getColumnName(1));
  }
  if (dirtyFlag_[2]) {
    ret.push_back(getColumnName(2));
  }
  if (dirtyFlag_[3]) {
    ret.push_back(getColumnName(3));
  }
  if (dirtyFlag_[4]) {
    ret.push_back(getColumnName(4));
  }
  if (dirtyFlag_[5]) {
    ret.push_back(getColumnName(5));
  }
  return ret;
}

void Questions::updateArgs(drogon::orm::internal::SqlBinder& binder) const {
  if (dirtyFlag_[1]) {
    if (getText()) {
      binder << getValueOfText();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[2]) {
    if (getCategoryId()) {
      binder << getValueOfCategoryId();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[3]) {
    if (getLanguage()) {
      binder << getValueOfLanguage();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[4]) {
    if (getMinAge()) {
      binder << getValueOfMinAge();
    } else {
      binder << nullptr;
    }
  }
  if (dirtyFlag_[5]) {
    if (getCreatedAt()) {
      binder << getValueOfCreatedAt();
    } else {
      binder << nullptr;
    }
  }
}
Json::Value Questions::toJson() const {
  Json::Value ret;
  if (getId()) {
    ret["id"] = (Json::Int64)getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getText()) {
    ret["text"] = getValueOfText();
  } else {
    ret["text"] = Json::Value();
  }
  if (getCategoryId()) {
    ret["category_id"] = (Json::Int64)getValueOfCategoryId();
  } else {
    ret["category_id"] = Json::Value();
  }
  if (getLanguage()) {
    ret["language"] = getValueOfLanguage();
  } else {
    ret["language"] = Json::Value();
  }
  if (getMinAge()) {
    ret["min_age"] = getValueOfMinAge();
  } else {
    ret["min_age"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  return ret;
}

std::string Questions::toString() const { return toJson().toStyledString(); }

Json::Value Questions::toMasqueradedJson(
    const std::vector<std::string>& pMasqueradingVector) const {
  Json::Value ret;
  if (pMasqueradingVector.size() == 6) {
    if (!pMasqueradingVector[0].empty()) {
      if (getId()) {
        ret[pMasqueradingVector[0]] = (Json::Int64)getValueOfId();
      } else {
        ret[pMasqueradingVector[0]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (getText()) {
        ret[pMasqueradingVector[1]] = getValueOfText();
      } else {
        ret[pMasqueradingVector[1]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (getCategoryId()) {
        ret[pMasqueradingVector[2]] = (Json::Int64)getValueOfCategoryId();
      } else {
        ret[pMasqueradingVector[2]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (getLanguage()) {
        ret[pMasqueradingVector[3]] = getValueOfLanguage();
      } else {
        ret[pMasqueradingVector[3]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (getMinAge()) {
        ret[pMasqueradingVector[4]] = getValueOfMinAge();
      } else {
        ret[pMasqueradingVector[4]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (getCreatedAt()) {
        ret[pMasqueradingVector[5]] = getCreatedAt()->toDbStringLocal();
      } else {
        ret[pMasqueradingVector[5]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if (getId()) {
    ret["id"] = (Json::Int64)getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getText()) {
    ret["text"] = getValueOfText();
  } else {
    ret["text"] = Json::Value();
  }
  if (getCategoryId()) {
    ret["category_id"] = (Json::Int64)getValueOfCategoryId();
  } else {
    ret["category_id"] = Json::Value();
  }
  if (getLanguage()) {
    ret["language"] = getValueOfLanguage();
  } else {
    ret["language"] = Json::Value();
  }
  if (getMinAge()) {
    ret["min_age"] = getValueOfMinAge();
  } else {
    ret["min_age"] = Json::Value();
  }
  if (getCreatedAt()) {
    ret["created_at"] = getCreatedAt()->toDbStringLocal();
  } else {
    ret["created_at"] = Json::Value();
  }
  return ret;
}

bool Questions::validateJsonForCreation(const Json::Value& pJson,
                                        std::string& err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, true)) return false;
  }
  if (pJson.isMember("text")) {
    if (!validJsonOfField(1, "text", pJson["text"], err, true)) return false;
  } else {
    err = "The text column cannot be null";
    return false;
  }
  if (pJson.isMember("category_id")) {
    if (!validJsonOfField(2, "category_id", pJson["category_id"], err, true))
      return false;
  } else {
    err = "The category_id column cannot be null";
    return false;
  }
  if (pJson.isMember("language")) {
    if (!validJsonOfField(3, "language", pJson["language"], err, true))
      return false;
  } else {
    err = "The language column cannot be null";
    return false;
  }
  if (pJson.isMember("min_age")) {
    if (!validJsonOfField(4, "min_age", pJson["min_age"], err, true))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(5, "created_at", pJson["created_at"], err, true))
      return false;
  }
  return true;
}
bool Questions::validateMasqueradedJsonForCreation(
    const Json::Value& pJson,
    const std::vector<std::string>& pMasqueradingVector, std::string& err) {
  if (pMasqueradingVector.size() != 6) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty()) {
      if (pJson.isMember(pMasqueradingVector[0])) {
        if (!validJsonOfField(0, pMasqueradingVector[0],
                              pJson[pMasqueradingVector[0]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (pJson.isMember(pMasqueradingVector[1])) {
        if (!validJsonOfField(1, pMasqueradingVector[1],
                              pJson[pMasqueradingVector[1]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[1] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[2].empty()) {
      if (pJson.isMember(pMasqueradingVector[2])) {
        if (!validJsonOfField(2, pMasqueradingVector[2],
                              pJson[pMasqueradingVector[2]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[2] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[3].empty()) {
      if (pJson.isMember(pMasqueradingVector[3])) {
        if (!validJsonOfField(3, pMasqueradingVector[3],
                              pJson[pMasqueradingVector[3]], err, true))
          return false;
      } else {
        err = "The " + pMasqueradingVector[3] + " column cannot be null";
        return false;
      }
    }
    if (!pMasqueradingVector[4].empty()) {
      if (pJson.isMember(pMasqueradingVector[4])) {
        if (!validJsonOfField(4, pMasqueradingVector[4],
                              pJson[pMasqueradingVector[4]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[5].empty()) {
      if (pJson.isMember(pMasqueradingVector[5])) {
        if (!validJsonOfField(5, pMasqueradingVector[5],
                              pJson[pMasqueradingVector[5]], err, true))
          return false;
      }
    }
  } catch (const Json::LogicError& e) {
    err = e.what();
    return false;
  }
  return true;
}
bool Questions::validateJsonForUpdate(const Json::Value& pJson,
                                      std::string& err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, false)) return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("text")) {
    if (!validJsonOfField(1, "text", pJson["text"], err, false)) return false;
  }
  if (pJson.isMember("category_id")) {
    if (!validJsonOfField(2, "category_id", pJson["category_id"], err, false))
      return false;
  }
  if (pJson.isMember("language")) {
    if (!validJsonOfField(3, "language", pJson["language"], err, false))
      return false;
  }
  if (pJson.isMember("min_age")) {
    if (!validJsonOfField(4, "min_age", pJson["min_age"], err, false))
      return false;
  }
  if (pJson.isMember("created_at")) {
    if (!validJsonOfField(5, "created_at", pJson["created_at"], err, false))
      return false;
  }
  return true;
}
bool Questions::validateMasqueradedJsonForUpdate(
    const Json::Value& pJson,
    const std::vector<std::string>& pMasqueradingVector, std::string& err) {
  if (pMasqueradingVector.size() != 6) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty() &&
        pJson.isMember(pMasqueradingVector[0])) {
      if (!validJsonOfField(0, pMasqueradingVector[0],
                            pJson[pMasqueradingVector[0]], err, false))
        return false;
    } else {
      err =
          "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[1].empty() &&
        pJson.isMember(pMasqueradingVector[1])) {
      if (!validJsonOfField(1, pMasqueradingVector[1],
                            pJson[pMasqueradingVector[1]], err, false))
        return false;
    }
    if (!pMasqueradingVector[2].empty() &&
        pJson.isMember(pMasqueradingVector[2])) {
      if (!validJsonOfField(2, pMasqueradingVector[2],
                            pJson[pMasqueradingVector[2]], err, false))
        return false;
    }
    if (!pMasqueradingVector[3].empty() &&
        pJson.isMember(pMasqueradingVector[3])) {
      if (!validJsonOfField(3, pMasqueradingVector[3],
                            pJson[pMasqueradingVector[3]], err, false))
        return false;
    }
    if (!pMasqueradingVector[4].empty() &&
        pJson.isMember(pMasqueradingVector[4])) {
      if (!validJsonOfField(4, pMasqueradingVector[4],
                            pJson[pMasqueradingVector[4]], err, false))
        return false;
    }
    if (!pMasqueradingVector[5].empty() &&
        pJson.isMember(pMasqueradingVector[5])) {
      if (!validJsonOfField(5, pMasqueradingVector[5],
                            pJson[pMasqueradingVector[5]], err, false))
        return false;
    }
  } catch (const Json::LogicError& e) {
    err = e.what();
    return false;
  }
  return true;
}
bool Questions::validJsonOfField(size_t index, const std::string& fieldName,
                                 const Json::Value& pJson, std::string& err,
                                 bool isForCreation) {
  switch (index) {
    case 0:
      if (pJson.isNull()) {
        err = "The " + fieldName + " column cannot be null";
        return false;
      }
      if (isForCreation) {
        err = "The automatic primary key cannot be set";
        return false;
      }
      if (!pJson.isInt64()) {
        err = "Type error in the " + fieldName + " field";
        return false;
      }
      break;
    case 1:
      if (pJson.isNull()) {
        err = "The " + fieldName + " column cannot be null";
        return false;
      }
      if (!pJson.isString()) {
        err = "Type error in the " + fieldName + " field";
        return false;
      }
      break;
    case 2:
      if (pJson.isNull()) {
        err = "The " + fieldName + " column cannot be null";
        return false;
      }
      if (!pJson.isInt64()) {
        err = "Type error in the " + fieldName + " field";
        return false;
      }
      break;
    case 3:
      if (pJson.isNull()) {
        err = "The " + fieldName + " column cannot be null";
        return false;
      }
      if (!pJson.isString()) {
        err = "Type error in the " + fieldName + " field";
        return false;
      }
      break;
    case 4:
      if (pJson.isNull()) {
        err = "The " + fieldName + " column cannot be null";
        return false;
      }
      if (!pJson.isInt()) {
        err = "Type error in the " + fieldName + " field";
        return false;
      }
      break;
    case 5:
      if (pJson.isNull()) {
        err = "The " + fieldName + " column cannot be null";
        return false;
      }
      if (!pJson.isString()) {
        err = "Type error in the " + fieldName + " field";
        return false;
      }
      break;
    default:
      err = "Internal error in the server";
      return false;
  }
  return true;
}
Categories Questions::getCategory(const DbClientPtr& clientPtr) const {
  static const std::string sql = "select * from categories where id = $1";
  Result r(nullptr);
  {
    auto binder = *clientPtr << sql;
    binder << *categoryId_ << Mode::Blocking >>
        [&r](const Result& result) { r = result; };
    binder.exec();
  }
  if (r.size() == 0) {
    throw UnexpectedRows("0 rows found");
  } else if (r.size() > 1) {
    throw UnexpectedRows("Found more than one row");
  }
  return Categories(r[0]);
}

void Questions::getCategory(const DbClientPtr& clientPtr,
                            const std::function<void(Categories)>& rcb,
                            const ExceptionCallback& ecb) const {
  static const std::string sql = "select * from categories where id = $1";
  *clientPtr << sql << *categoryId_ >> [rcb = std::move(rcb),
                                        ecb](const Result& r) {
    if (r.size() == 0) {
      ecb(UnexpectedRows("0 rows found"));
    } else if (r.size() > 1) {
      ecb(UnexpectedRows("Found more than one row"));
    } else {
      rcb(Categories(r[0]));
    }
  } >> ecb;
}
Languages Questions::getLanguage(const DbClientPtr& clientPtr) const {
  static const std::string sql = "select * from languages where code = $1";
  Result r(nullptr);
  {
    auto binder = *clientPtr << sql;
    binder << *language_ << Mode::Blocking >>
        [&r](const Result& result) { r = result; };
    binder.exec();
  }
  if (r.size() == 0) {
    throw UnexpectedRows("0 rows found");
  } else if (r.size() > 1) {
    throw UnexpectedRows("Found more than one row");
  }
  return Languages(r[0]);
}

void Questions::getLanguage(const DbClientPtr& clientPtr,
                            const std::function<void(Languages)>& rcb,
                            const ExceptionCallback& ecb) const {
  static const std::string sql = "select * from languages where code = $1";
  *clientPtr << sql << *language_ >> [rcb = std::move(rcb),
                                      ecb](const Result& r) {
    if (r.size() == 0) {
      ecb(UnexpectedRows("0 rows found"));
    } else if (r.size() > 1) {
      ecb(UnexpectedRows("Found more than one row"));
    } else {
      rcb(Languages(r[0]));
    }
  } >> ecb;
}
std::vector<AnswerOptions> Questions::getAnswerOptions(
    const DbClientPtr& clientPtr) const {
  static const std::string sql =
      "select * from answer_options where question_id = $1";
  Result r(nullptr);
  {
    auto binder = *clientPtr << sql;
    binder << *id_ << Mode::Blocking >>
        [&r](const Result& result) { r = result; };
    binder.exec();
  }
  std::vector<AnswerOptions> ret;
  ret.reserve(r.size());
  for (auto const& row : r) {
    ret.emplace_back(AnswerOptions(row));
  }
  return ret;
}

void Questions::getAnswerOptions(
    const DbClientPtr& clientPtr,
    const std::function<void(std::vector<AnswerOptions>)>& rcb,
    const ExceptionCallback& ecb) const {
  static const std::string sql =
      "select * from answer_options where question_id = $1";
  *clientPtr << sql << *id_ >> [rcb = std::move(rcb)](const Result& r) {
    std::vector<AnswerOptions> ret;
    ret.reserve(r.size());
    for (auto const& row : r) {
      ret.emplace_back(AnswerOptions(row));
    }
    rcb(ret);
  } >> ecb;
}
std::vector<UserAnswers> Questions::getUserAnswers(
    const DbClientPtr& clientPtr) const {
  static const std::string sql =
      "select * from user_answers where question_id = $1";
  Result r(nullptr);
  {
    auto binder = *clientPtr << sql;
    binder << *id_ << Mode::Blocking >>
        [&r](const Result& result) { r = result; };
    binder.exec();
  }
  std::vector<UserAnswers> ret;
  ret.reserve(r.size());
  for (auto const& row : r) {
    ret.emplace_back(UserAnswers(row));
  }
  return ret;
}

void Questions::getUserAnswers(
    const DbClientPtr& clientPtr,
    const std::function<void(std::vector<UserAnswers>)>& rcb,
    const ExceptionCallback& ecb) const {
  static const std::string sql =
      "select * from user_answers where question_id = $1";
  *clientPtr << sql << *id_ >> [rcb = std::move(rcb)](const Result& r) {
    std::vector<UserAnswers> ret;
    ret.reserve(r.size());
    for (auto const& row : r) {
      ret.emplace_back(UserAnswers(row));
    }
    rcb(ret);
  } >> ecb;
}
